import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import 'package:intl/intl.dart';
import '../utils/currency_utils.dart';

class PdfReportService {
  static Future<void> generateUserReport({
    required Map<String, dynamic> user,
    required Map<String, dynamic> stats,
    required List<dynamic> transactions,
  }) async {
    final pdf = pw.Document();
    final dateStr = DateFormat('MMMM dd, yyyy').format(DateTime.now());

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(32),
        build: (context) => [
          _buildHeader(user, dateStr),
          pw.SizedBox(height: 20),
          _buildSummary(stats),
          pw.SizedBox(height: 20),
          _buildTransactionTable(transactions),
          pw.Padding(
            padding: const pw.EdgeInsets.only(top: 40),
            child: pw.Center(
              child: pw.Text(
                'Generated by Wise Wallet - Smart Financial Management',
                style: pw.TextStyle(fontSize: 10, color: PdfColors.grey700),
              ),
            ),
          ),
        ],
      ),
    );

    await Printing.layoutPdf(
      onLayout: (PdfPageFormat format) async => pdf.save(),
      name: 'Report_${user['name'].toString().replaceAll(' ', '_')}.pdf',
    );
  }

  static pw.Widget _buildHeader(Map<String, dynamic> user, String date) {
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        pw.Row(
          mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
          children: [
            pw.Text(
              'Wise Wallet',
              style: pw.TextStyle(
                fontSize: 24,
                fontWeight: pw.FontWeight.bold,
                color: PdfColors.indigo900,
              ),
            ),
            pw.Text(
              'USER FINANCIAL REPORT',
              style: pw.TextStyle(
                fontSize: 12,
                fontWeight: pw.FontWeight.bold,
                color: PdfColors.grey700,
              ),
            ),
          ],
        ),
        pw.Divider(thickness: 2, color: PdfColors.indigo900),
        pw.SizedBox(height: 10),
        pw.Row(
          mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
          children: [
            pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                pw.Text('Report For:', style: pw.TextStyle(fontWeight: pw.FontWeight.bold)),
                pw.Text(user['name']?.toString() ?? 'N/A', style: pw.TextStyle(fontSize: 16, fontWeight: pw.FontWeight.bold)),
                pw.Text(user['email']?.toString() ?? 'N/A', style: pw.TextStyle(color: PdfColors.grey700)),
              ],
            ),
            pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.end,
              children: [
                pw.Text('Date Generated:', style: pw.TextStyle(fontWeight: pw.FontWeight.bold)),
                pw.Text(date),
              ],
            ),
          ],
        ),
      ],
    );
  }

  static pw.Widget _buildSummary(Map<String, dynamic> stats) {
    return pw.Container(
      padding: const pw.EdgeInsets.all(15),
      decoration: const pw.BoxDecoration(
        color: PdfColors.grey100,
        borderRadius: pw.BorderRadius.all(pw.Radius.circular(8)),
      ),
      child: pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Text('Financial Summary', style: pw.TextStyle(fontSize: 16, fontWeight: pw.FontWeight.bold)),
          pw.SizedBox(height: 10),
          pw.Row(
            mainAxisAlignment: pw.MainAxisAlignment.spaceAround,
            children: [
              _buildSummaryItem('Total Income', (stats['totalIncome'] ?? 0.0).toDouble(), PdfColors.green900),
              _buildSummaryItem('Total Expenses', (stats['totalExpenses'] ?? 0.0).toDouble(), PdfColors.red900),
              _buildSummaryItem('Net Balance', (stats['netBalance'] ?? 0.0).toDouble(), PdfColors.indigo900),
            ],
          ),
        ],
      ),
    );
  }

  static pw.Widget _buildSummaryItem(String label, double amount, PdfColor color) {
    return pw.Column(
      children: [
        pw.Text(label, style: const pw.TextStyle(fontSize: 10)),
        pw.SizedBox(height: 4),
        pw.Text(
          CurrencyUtils.format(amount),
          style: pw.TextStyle(fontSize: 14, fontWeight: pw.FontWeight.bold, color: color),
        ),
      ],
    );
  }

  static pw.Widget _buildTransactionTable(List<dynamic> transactions) {
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        pw.Text('Recent Transactions', style: pw.TextStyle(fontSize: 16, fontWeight: pw.FontWeight.bold)),
        pw.SizedBox(height: 10),
        pw.Table(
          border: pw.TableBorder.all(color: PdfColors.grey300),
          columnWidths: {
            0: const pw.FlexColumnWidth(2),
            1: const pw.FlexColumnWidth(3),
            2: const pw.FlexColumnWidth(2),
            3: const pw.FlexColumnWidth(2),
          },
          children: [
            // Header
            pw.TableRow(
              decoration: const pw.BoxDecoration(color: PdfColors.grey300),
              children: [
                _tableHeader('Date'),
                _tableHeader('Category'),
                _tableHeader('Type'),
                _tableHeader('Amount'),
              ],
            ),
            // Data Rows
            ...transactions.map((tx) {
              final isExpense = tx['type'] == 'expense';
              final date = DateTime.parse(tx['date']?.toString() ?? DateTime.now().toIso8601String());
              return pw.TableRow(
                children: [
                  _tableCell(DateFormat('MMM dd, yyyy').format(date)),
                  _tableCell(tx['category']?.toString() ?? 'General'),
                  _tableCell(tx['type'].toString().toUpperCase(), 
                    color: isExpense ? PdfColors.red900 : PdfColors.green900),
                  _tableCell(CurrencyUtils.format((tx['amount'] ?? 0.0).toDouble()),
                    align: pw.TextAlign.right,
                    fontWeight: pw.FontWeight.bold),
                ],
              );
            }),
          ],
        ),
      ],
    );
  }

  static pw.Widget _tableHeader(String text) {
    return pw.Padding(
      padding: const pw.EdgeInsets.all(8),
      child: pw.Text(text, style: pw.TextStyle(fontWeight: pw.FontWeight.bold)),
    );
  }

  static pw.Widget _tableCell(String text, {PdfColor? color, pw.TextAlign align = pw.TextAlign.left, pw.FontWeight? fontWeight}) {
    return pw.Padding(
      padding: const pw.EdgeInsets.all(8),
      child: pw.Text(
        text,
        textAlign: align,
        style: pw.TextStyle(color: color, fontWeight: fontWeight, fontSize: 10),
      ),
    );
  }
}
